/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 uranus.gltf 
Author: Recourse Design ltd. (https://sketchfab.com/RecourseDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/uranus-7cd8afee13fc470ca4ddd5d5088b07fc
Title: Uranus
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/uranus.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Earth_Planet_0.geometry} material={materials.Planet} />
    </group>
  )
}

useGLTF.preload('/uranus.gltf')
