/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 neptune.gltf 
Author: Recourse Design ltd. (https://sketchfab.com/RecourseDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neptune-9263a7336bb245e893fef236e4f3874e
Title: Neptune
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/neptune.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Earth_Planet_0.geometry} material={materials.Planet} />
    </group>
  )
}

useGLTF.preload('/neptune.gltf')
