/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 venus.gltf 
Author: Recourse Design ltd. (https://sketchfab.com/RecourseDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/venus-e8dc5d996178422fa55d7fe0174c4568
Title: Venus
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/venus.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Clouds_Clouds_0.geometry} material={materials.Clouds} />
      <mesh geometry={nodes.Earth_Planet_0.geometry} material={materials.Planet} />
    </group>
  )
}

useGLTF.preload('/venus.gltf')
