/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 moon.gltf 
Author: Recourse Design ltd. (https://sketchfab.com/RecourseDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-724ace0d0c834ad5927206fafd516958
Title: Moon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/moon.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Earth_Planet_0.geometry} material={materials.Planet} />
    </group>
  )
}

useGLTF.preload('/moon.gltf')
