/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 saturn.gltf 
Author: Recourse Design ltd. (https://sketchfab.com/RecourseDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/saturn-38bbb2181de64e22ad11a2884d270971
Title: Saturn
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/saturn.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.687, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Mesh_(7)_Rings_0'].geometry} material={materials.Rings} />
          <mesh geometry={nodes.Earth_Planet_0.geometry} material={materials.Planet} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/saturn.gltf')
