/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 mercury.gltf 
Author: Recourse Design ltd. (https://sketchfab.com/RecourseDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mercury-bc229dccc66b439ebe5fe4a80c4e535a
Title: Mercury
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Mercury() {
  const { scene } = useGLTF('./mercury.gltf');
  return <primitive object={scene} scale={[0.5, 0.5, 0.5]} />;
}

useGLTF.preload('./mercury.gltf');
